---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-test-app
spec:
  selector:
    matchLabels:
      app: python-test-app
  replicas: 1
  template:
    metadata:
      labels:
        app: python-test-app
      annotations:
        instrumentation.newrelic.com/inject-python: "true"
    spec:
      containers:
        - name: python-test-app
          image: e2e/python_test_app:e2e
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-test-app-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: python-test-app 
