---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-app
      annotations:
        instrumentation.newrelic.com/inject-python: "true"
    spec:
      containers:
      - name: flask-app
        image: e2e/python_test_app
        ports:
          - containerPort: 5000
